# Generated by Django 3.1.8 on 2021-04-20 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='availableproducts',
            table='products',
        ),
    ]
