# Generated by Django 3.1.8 on 2021-05-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=125)),
                ('quantity', models.IntegerField()),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('supplier_id', models.CharField(max_length=125)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
