# Generated by Django 3.1.8 on 2021-05-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availableproducts',
            old_name='wholesale_price',
            new_name='wholesale_cost',
        ),
    ]
