# Generated by Django 3.1.8 on 2021-05-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210504_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availableproducts',
            name='id',
        ),
        migrations.AlterField(
            model_name='availableproducts',
            name='product_id',
            field=models.CharField(max_length=125, primary_key=True, serialize=False),
        ),
    ]
