# Generated by Django 3.1.8 on 2021-05-04 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210504_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availableproducts',
            old_name='wholesale_cost',
            new_name='wholesale_price',
        ),
    ]
