# Generated by Django 3.1.8 on 2021-05-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210504_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=125, primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=125)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('author_id', models.CharField(max_length=125)),
                ('address', models.CharField(max_length=125)),
                ('city', models.CharField(max_length=125)),
                ('state', models.CharField(max_length=125)),
                ('zip', models.CharField(max_length=125)),
                ('status', models.CharField(max_length=125)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
